"""initial migration

Revision ID: 3b938a60d1eb
Revises:
Create Date: 2026-06-14 14:58:16.595563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3b938a60d1eb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column(
            "admin_email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
        sa.Column("admin_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_org_admin_token"), "org", ["admin_token"], unique=True)
    op.create_index(op.f("ix_org_slug"), "org", ["slug"], unique=True)
    op.create_table(
        "shift",
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column(
            "location", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "notes", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shift_org_id"), "shift", ["org_id"], unique=False)
    op.create_table(
        "signup",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shift_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shift.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signup_shift_id"), "signup", ["shift_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signup_shift_id"), table_name="signup")
    op.drop_table("signup")
    op.drop_index(op.f("ix_shift_org_id"), table_name="shift")
    op.drop_table("shift")
    op.drop_index(op.f("ix_org_slug"), table_name="org")
    op.drop_index(op.f("ix_org_admin_token"), table_name="org")
    op.drop_table("org")
    # ### end Alembic commands ###
