/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgRouteRouteImport } from './routes/org/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugRouteRouteImport } from './routes/org/$slug/route'
import { Route as OrgSlugIndexRouteImport } from './routes/org/$slug/index'
import { Route as OrgSlugAdminRouteImport } from './routes/org/$slug/admin'
import { Route as OrgSlugShiftShiftIdRouteImport } from './routes/org/$slug/shift/$shiftId'

const OrgRouteRoute = OrgRouteRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugAdminRoute = OrgSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugShiftShiftIdRoute = OrgSlugShiftShiftIdRouteImport.update({
  id: '/shift/$shiftId',
  path: '/shift/$shiftId',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/org': typeof OrgRouteRouteWithChildren
  '/org/$slug': typeof OrgSlugRouteRouteWithChildren
  '/org/$slug/admin': typeof OrgSlugAdminRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/org/$slug/shift/$shiftId': typeof OrgSlugShiftShiftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/org': typeof OrgRouteRouteWithChildren
  '/org/$slug/admin': typeof OrgSlugAdminRoute
  '/org/$slug': typeof OrgSlugIndexRoute
  '/org/$slug/shift/$shiftId': typeof OrgSlugShiftShiftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/org': typeof OrgRouteRouteWithChildren
  '/org/$slug': typeof OrgSlugRouteRouteWithChildren
  '/org/$slug/admin': typeof OrgSlugAdminRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/org/$slug/shift/$shiftId': typeof OrgSlugShiftShiftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/org'
    | '/org/$slug'
    | '/org/$slug/admin'
    | '/org/$slug/'
    | '/org/$slug/shift/$shiftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/org'
    | '/org/$slug/admin'
    | '/org/$slug'
    | '/org/$slug/shift/$shiftId'
  id:
    | '__root__'
    | '/'
    | '/org'
    | '/org/$slug'
    | '/org/$slug/admin'
    | '/org/$slug/'
    | '/org/$slug/shift/$shiftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgRouteRoute: typeof OrgRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug': {
      id: '/org/$slug'
      path: '/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugRouteRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/$slug/': {
      id: '/org/$slug/'
      path: '/'
      fullPath: '/org/$slug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/org/$slug/admin': {
      id: '/org/$slug/admin'
      path: '/admin'
      fullPath: '/org/$slug/admin'
      preLoaderRoute: typeof OrgSlugAdminRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/org/$slug/shift/$shiftId': {
      id: '/org/$slug/shift/$shiftId'
      path: '/shift/$shiftId'
      fullPath: '/org/$slug/shift/$shiftId'
      preLoaderRoute: typeof OrgSlugShiftShiftIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
  }
}

interface OrgSlugRouteRouteChildren {
  OrgSlugAdminRoute: typeof OrgSlugAdminRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugShiftShiftIdRoute: typeof OrgSlugShiftShiftIdRoute
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugAdminRoute: OrgSlugAdminRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugShiftShiftIdRoute: OrgSlugShiftShiftIdRoute,
}

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
)

interface OrgRouteRouteChildren {
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren
}

const OrgRouteRouteChildren: OrgRouteRouteChildren = {
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
}

const OrgRouteRouteWithChildren = OrgRouteRoute._addFileChildren(
  OrgRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgRouteRoute: OrgRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
